version: '3.4'

services:
  to.frontend:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"
    volumes:
      - type: bind
        source: ./data
        target: /TotalOrder

