version: '3.4'

services:
  to.frontend:
    image: tofrontend:dev
    build:
      target: build
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      #- NUGET_FALLBACK_PACKAGES=$container_paths_to_fallback_packages_to.frontend$
    volumes:
      - C:\_cc\swyx_1\TotalOrderCore\src\to.frontend\to.frontend:/app
      - C:\Users\georg.brzyk\vsdbg\vs2017u5:/remote_debugger:ro
#$nuget_volume_mapping_to.frontend$
    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      #com.microsoft.visualstudio.debuggee.arguments: " $debuggee_arguments_probing_paths_to.frontend$ bin/Debug/netcoreapp2.0/to.frontend.dll"
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/bash -c \"if PID=$$(pidof -x dotnet); then kill $$PID; fi\""
