name: Docker Image CI

on: [push]

jobs:

  build:
 
    runs-on: ubuntu-18.04
 
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Login
      env:
        DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
      run: echo ${DOCKERHUB_PASSWORD} | docker login --username=${DOCKERHUB_USERNAME} --password-stdin
     
    - name: Build
      run: docker build . --file src/to.frontend/to.frontend/Dockerfile --tag swyx/totalorder:${GITHUB_SHA}
      
    - name: Push
      run: docker push swyx/totalorder:${GITHUB_SHA}

  